# Generated by Django 3.2.8 on 2021-10-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Some Category', max_length=240),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Some description'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://jsonplaceholder.typicode.com/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
